// examples/module1/lesson5/users-crm-react/src/components/UsersList.tsx
import { useState, useEffect } from 'react';
import type { User } from '../model/User';
import { getStatusColor } from '../utils/statusColors';

const UsersList = () => {
  const [users, setUsers] = useState<User[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchUsers = async () => {
    try {
      const response = await fetch('http://localhost:3000/api/data/users');
      if (!response.ok) throw new Error('Failed to fetch users');
      const data = await response.json();
      setUsers(data);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'An error occurred');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchUsers();
  }, []);

  if (loading) return <div>Loading users...</div>;
  if (error) return <div>Error: {error}</div>;

  return (
    <div className="grid gap-4" data-testid="users-list">
      {users.map((user) => (
        <div
          key={user.id}
          data-testid="user-item"
          className="bg-white rounded-lg shadow p-4 flex justify-between items-center"
        >
          <div className="flex flex-row justify-between items-center w-full">
            <h3 className="text-lg font-semibold">{user.name}</h3>
            <span
              className={`px-2 py-1 rounded-lg text-sm font-medium ${getStatusColor(
                user.status
              )}`}
            >
              {user.status}
            </span>
          </div>
        </div>
      ))}
    </div>
  );
};

export default UsersList;

// examples/module1/lesson5/users-crm-svelte/src/components/UsersList.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { User } from '../model/User';
  import { getStatusColor } from '../utils/statusColors';

  let users = $state<User[]>([]);
  let loading = $state(true);
  let error = $state<string | null>(null);

  const fetchUsers = async () => {
    try {
      const response = await fetch('http://localhost:3000/api/data/users');
      if (!response.ok) throw new Error('Failed to fetch users');
      const data = await response.json();
      users = data;
    } catch (e) {
      error = e instanceof Error ? e.message : 'An error occurred';
    } finally {
      loading = false;
    }
  };

  onMount(fetchUsers);
</script>

{#if loading}
  <div>Loading users...</div>
{:else if error}
  <div>Error: {error}</div>
{:else}
  <div class="grid gap-4" data-testid="users-list">
    {#each users as user (user.id)}
      <div
        class="bg-white rounded-lg shadow p-4 flex justify-between items-center"
        data-testid="user-item"
      >
        <div class="flex flex-row justify-between items-center w-full">
          <h3 class="text-lg font-semibold">{user.name}</h3>
          <span
            class={`px-2 py-1 rounded-lg text-sm font-medium ${getStatusColor(
              user.status,
            )}`}
          >
            {user.status}
          </span>
        </div>
      </div>
    {/each}
  </div>
{/if}
