// examples/module1/lesson2/prop-drilling-start/components/NameField.tsx
export function NameField({
  name,
  setName,
}: {
  name: string;
  setName: React.Dispatch<React.SetStateAction<string>>;
}) {
  return (
    <label className="flex flex-col">
      Name
      <input
        className="border h-7 mt-1 indent-2"
        type="text"
        placeholder="Rick Sanchez..."
        value={name}
        onChange={(e) => setName(e.target.value)}
      />
    </label>
  );
}

// examples/module1/lesson2/signals-angular-finish/src/app/components/name-field/name-field.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-name-field',
  standalone: true,
  imports: [],
  template: `<label class="flex flex-col">
    Name
    <input
      class="border h-7 mt-1 indent-2"
      type="text"
      placeholder="Name"
      [value]="name"
      (input)="onNameChange($event)"
    />
  </label>`,
  styleUrl: './name-field.component.scss',
})
export class NameFieldComponent {
  @Input() name: string = '';
  @Output() nameChange = new EventEmitter<string>();

  onNameChange(event: Event) {
    const value = (event.target as HTMLInputElement).value;
    this.nameChange.emit(value);
  }
}
