// examples/module1/lesson1/solver/components/Input.tsx
import React, { FC, ReactElement } from 'react';

type InputProps = {
  value: number,
  onChange: (a: number) => void
};

const Input: FC<InputProps> = ({ value, onChange }): ReactElement => {
  return <input
    type='number'
    className='rounded-md shadow-md p-4'
    value={value}
    onChange={(e) => onChange(parseFloat(e.target.value))}
  />;
};

export default Input;

// practice/vue-app/src/components/Input.vue
<script setup lang="ts">
import { defineProps } from 'vue';

defineProps<{ modelValue: number | "", isValid: boolean }>();
</script>

<template>
  <div>
    <input
      :value="modelValue"
      type="number"
      class="rounded-md shadow-md p-4 w-full"
      @input="$emit('update:modelValue', $event.target?.value)"
    />
    <p v-if="!isValid" class="text-red-500">Invalid input</p>
  </div>
</template>

<style scoped>

</style>
