// examples/module1/lesson1/validate-it/components/TextField.tsx
interface TextFieldProps {
  type?: string;
  id?: string;
  placeholder: string;
  onChange?: (event: React.ChangeEvent<HTMLInputElement>) => void;
  value: string | number | undefined;
}

export function TextField({
  type = 'text',
  id = 'input',
  placeholder,
  value,
  onChange,
}: TextFieldProps) {
  return (
    <input
      className="rounded-md p-4 shadow-lg"
      type={type}
      id={id}
      value={value}
      placeholder={placeholder}
      onChange={onChange}
    />
  );
}

export default TextField;

// practice/vue-app/src/components/TextField.vue
<script setup lang="ts">
import { defineModel } from 'vue';

const inputValue = defineModel<string>();

defineProps({
  placeholder: {
    type: String,
    required: false
  }
});

</script>

<template>
  <input
    v-model="inputValue"
    class="rounded-md p-4 shadow-lg"
    type="text"
    :placeholder="placeholder"
  />
</template>

<style scoped></style>
