// practice/module1/lesson2/countries-api/src/components/SelectInput.vue
<script setup lang="ts">
import { ref } from 'vue';

interface SelectInputOption {
  value: string;
  label: string;
}

defineProps({
  label: {
    type: String,
    required: true,
  },
  options: {
    type: Array as () => SelectInputOption[],
    required: true,
  },
});

const select = ref('alphabetical');
const emit = defineEmits(['onChange']);
</script>

<template>
  <label>
    {{ label }}:&nbsp;
    <select v-model="select" @change="emit('onChange', select)">
      <option
        v-for="option in options"
        :key="option.value"
        :value="option.value"
      >
        {{ option.label }}
      </option>
    </select>
  </label>
</template>

// examples/module1/lesson2/container-components/components/SelectInput.tsx
type SelectInputProps = {
  label: string;
  value: string;
  onChange: (value: string) => void;
  options: { value: string; label: string }[];
};

function SelectInput({ label, value, onChange, options }: SelectInputProps) {
  return (
    <label className="flex flex-col">
      {label}
      <select
        value={value}
        onChange={(e) => onChange(e.target.value)}
        className="mt-1 border h-7"
      >
        {options.map((option) => (
          <option key={option.value} value={option.value}>
            {option.label}
          </option>
        ))}
      </select>
    </label>
  );
}

export default SelectInput;
