// examples/module1/lesson2/signals-angular-start/src/app/components/sort-select/sort-select.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
    selector: 'app-sort-select',
    imports: [],
    template: `
    <label class="flex flex-col">
      Sort by
      <select
        [value]="sortOption"
        (change)="onSortOptionChange($event)"
        class="border h-7 mt-1"
      >
        <option value="">Initial</option>
        <option value="name">Name</option>
        <option value="created">Created Date</option>
      </select>
    </label>
  `,
    styleUrl: './sort-select.component.scss'
})
export class SortSelectComponent {
  @Input() sortOption: string = '';
  @Output() sortOptionChange = new EventEmitter<string>();

  onSortOptionChange(event: Event) {
    const value = (event.target as HTMLSelectElement).value;
    this.sortOptionChange.emit(value);
  }
}

// examples/module1/lesson2/container-components/components/SortSelect.tsx
type SortSelectProps = {
  onChange: (event: React.ChangeEvent<HTMLSelectElement>) => void;
  sortOption: string;
};

const SortSelect = ({ onChange, sortOption }: SortSelectProps) => {
  return (
    <label className="flex flex-col">
      Sort by
      <select
        value={sortOption}
        onChange={onChange}
        className="border h-7 mt-1"
      >
        <option value="">Initial</option>
        <option value="name">Name</option>
        <option value="created">Created Date</option>
      </select>
    </label>
  );
};

export default SortSelect;
