// practice/module1/lesson2/countries-api/src/components/TextInput.vue
<script setup lang="ts">
import { ref } from 'vue';

defineProps({
  label: {
    type: String,
    required: true,
  },
  placeholder: {
    type: String,
    required: true,
  },
});

const input = ref('');
const emit = defineEmits(['onChange']);
</script>

<template>
  <label>
    {{ label }}:&nbsp;
    <input
      v-model="input"
      type="text"
      :placeholder="placeholder"
      @input="emit('onChange', input)"
    />
  </label>
</template>

// examples/module1/lesson2/container-components/components/TextInput.tsx
type TextInputProps = {
  label: string;
  value: string;
  onChange: (value: string) => void;
  placeholder?: string;
};

export const TextInput = ({
  label,
  value,
  onChange,
  placeholder,
}: TextInputProps) => {
  return (
    <label className="flex flex-col">
      {label}
      <input
        className="mt-1 border h-7 indent-2"
        type="text"
        placeholder={placeholder}
        value={value}
        onChange={(e) => onChange(e.target.value)}
      />
    </label>
  );
};
