// examples/module1/lesson2/_solutions/countries-search/components/CountryList.tsx
import React from 'react';
import { Country } from '../types';
import CountryCard from './CountryCard';

interface CountryListProps {
  countries: Country[];
}

const CountryList = ({ countries }: CountryListProps) => {
  return (
    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
      {countries.map((country) => (
        <CountryCard key={country.cca3} country={country} />
      ))}
    </div>
  );
};

export default CountryList;

// practice/module1/lesson2/countries-api/src/components/CountryList.vue
<script setup lang="ts">
import CountryCard from './CountryCard.vue';
import { Country } from '../types/Country';

defineProps({
  countries: {
    type: Array as () => Country[],
    required: true,
  },
});
</script>

<template>
  <ol>
    <li v-for="country in countries" :key="country.cca3">
      <CountryCard :country="country" />
    </li>
  </ol>
</template>

<style scoped>
ol {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  justify-content: center;
  list-style: none;
  padding: 20px 0;
  margin: 0;

  li {
    display: flex;
    width: 300px;
  }
}
</style>
