// examples/module1/lesson2/countries/countries/src/app/components/countries-list/countries-list.component.ts
import { Component, OnInit } from '@angular/core';

import { CountryService } from "../../services/country.service";

@Component({
  selector: 'app-countries-list',
  templateUrl: './countries-list.component.html',
  styleUrls: ['./countries-list.component.scss']
})
export class CountriesListComponent implements OnInit {
  countries: any[] = [];

  constructor(private countryService: CountryService) {}

  ngOnInit(): void {
    this.countryService.countries$.subscribe((data) => {
      this.countries = data;
    });
  }
}

<ol class="country-grid">
  <li class="country-item" *ngFor="let country of countries">
    <img class="flag" [src]="country.flags.png" alt="{{ country.name.common }} flag">
    <h2>{{ country.name.common }}</h2>
  </li>
</ol>

// examples/module1/lesson2/countries/components/CountriesList.tsx
import { Countries } from '../types/Countries';
interface CountriesListProps {
  countries: Countries[];
}

export const CountriesList = ({ countries }: CountriesListProps) => {
  return (
    <ol className="grid grid-cols-1 gap-4 list-none md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
      {countries.map((country) => (
        <li key={country.id} className="flex flex-col items-center">
          <img src={country.flags.png} alt={country.flags.alt} />
          <h2>{country.name.common}</h2>
        </li>
      ))}
    </ol>
  );
};
