// examples/module1/lesson5/_solutions/users-crm-svelte/src/components/StatusStats.svelte
<script lang="ts">
  import { useUsers } from '../hooks/useUsers';
  import { getStatusColor } from '../utils/statusColors';
  import type { User } from '../model/User';

  const users = useUsers();
  let statusCounts = $state<Record<string, number>>({});

  $effect(() => {
    if ($users.data) {
      statusCounts = $users.data.reduce(
        (acc: Record<string, number>, user: User) => {
          acc[user.status] = (acc[user.status] || 0) + 1;
          return acc;
        },
        {},
      );
    }
  });
</script>

{#if $users.isLoading}
  <div>Loading stats...</div>
{:else if $users.isError}
  <div>Error: {$users.error.message}</div>
{:else}
  <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mb-8">
    {#each Object.entries(statusCounts) as [status, count]}
      <div
        class="bg-white rounded-lg shadow p-4"
        data-testid="status-stats-item"
      >
        <div class="flex flex-col items-center">
          <span
            class={`px-2 py-1 rounded-lg text-sm font-medium mb-2 ${getStatusColor(
              status,
            )}`}
          >
            {status}
          </span>
          <span class="text-2xl font-bold">{count}</span>
        </div>
      </div>
    {/each}
  </div>
{/if}

// examples/module1/lesson5/users-crm-react/src/components/StatusStats.tsx
import { useState, useEffect, useMemo } from 'react';
import type { User } from '../model/User';
import { getStatusColor } from '../utils/statusColors';
import { useFetchUsers } from '../hooks/useFetchUsers';


const StatusStats = () => {
  const [users, setUsers] = useState<User[]>([]);
  const { isPending, error, data } = useFetchUsers();

  const fetchUsers = async () => {
     if (data) {
      setUsers(data);
    }
  };

  useEffect(() => {
    fetchUsers();
  }, [data]);

  const statusCounts = useMemo(() => {
    return users.reduce((acc: Record<string, number>, user: User) => {
      acc[user.status] = (acc[user.status] || 0) + 1;
      return acc;
    }, {});
  }, [users]);

  if (isPending) return <div>Loading stats...</div>;
  if (error) return <div>Error: {error.message}</div>;

  return (
    <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mb-8">
      {Object.entries(statusCounts).map(([status, count]) => (
        <div
          key={status}
          className="bg-white rounded-lg shadow p-4"
          data-testid="status-stats-item"
        >
          <div className="flex flex-col items-center">
            <span
              className={`px-2 py-1 rounded-lg text-sm font-medium mb-2 ${getStatusColor(
                status
              )}`}
            >
              {status}
            </span>
            <span className="text-2xl font-bold">{count}</span>
          </div>
        </div>
      ))}
    </div>
  );
};

export default StatusStats;
