// examples/module1/lesson2/container-components/components/CharacterCard.tsx
import React from "react";
import { Character } from "../types/Character";

function CharacterCard({ character }: { character: Character }) {

  return (
    <li className="flex flex-col items-center">
          <h3>{character.name}</h3>
          <img src={character.image} alt={character.name} />
        </li>
  )
}

export default CharacterCard;

// examples/module1/lesson2/signals-angular-start/src/app/components/character-card/character-card.component.ts
import { Component, Input } from '@angular/core';
import { Character } from '../../types/Character';

@Component({
    selector: 'app-character-card',
    imports: [],
    template: `
    <h3>{{ character.name }}</h3>
    <img [src]="character.image" [alt]="character.name" />
  `,
    styleUrl: './character-card.component.scss'
})
export class CharacterCardComponent {
  @Input() character!: Character;
}
